### ISSUE TITLE
Notifikasi Selalu Memberikan Data Restoran Yang Sama

### ISSUE THREAD

**Issue by PhilipPurwoko** [PhilipPurwoko/ranked-resto#3]
Saat membuat `scheduled notification`, notifikasi selalu memberikan data restoran yang sama terus menerus. Misalnya jika yang muncul _Kafein_, maka seterusnya _Kafein_ terus dan `restaurants.shuffle()` hanya berjalan satu kali. Apakah harus menggunakan push notification ? Bagaimana solusinya. Terima kasih

https://github.com/PhilipPurwoko/ranked-resto/blob/9a937e97178d8998770747d84ca5e0370a87ae56/lib/functions/notification.dart#L5-L29

https://github.com/PhilipPurwoko/ranked-resto/blob/9a937e97178d8998770747d84ca5e0370a87ae56/lib/screen/setting_screen.dart#L35-L69

**Comment by rllyhz** [comment]
Harusnya fetching api dilakukan tiap kali notification akan di notified, bukan ketika notification di register untuk daily notify dan mengirimkan data yang sama

**Comment by rllyhz** [comment]
Dan mungkin itu juga memang default behavior dari library notifikasi nya.. Di buat sekali dan akan memunculkan notifikasi berulang dengan data yang sama pertama kali di kirimkan ke parameternya.

**Comment by tioirawan** [comment]
Untuk kasus ini harus menggunakan background service mas, tidak cukup menggunakan scheduled notification saja, karena kita butuh melakukan fetching data tiap kali pengingat dijalankan. Jadi data restoran harus diambil dan dipilih secara acak pada background service

**Comment by PhilipPurwoko** [comment]
Baik. Bisa dimengerti. Terima kasih @indmind @rllyhz
